# Configurations
title:           Pycon Workshop Bloomreach
longtitle:        Pycon Workshop Bloomreach
author:           Ondrej Unger
email:            ondrej.unger@bloomreach.com
description: >- # this means to ignore newlines until
  On Pycon 2022 Bloomreach reveals their hiring assignment. On this pages are documents describing how to implement it, 
  and questions that will help you to understand better the assignment and things used in the implementation.

version:          1.0
gitbook_version:  3.2.3

url:              'https://uondro.github.io/pycon-2022'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.png

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
